//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store2DoorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
           
            this.Cart_Item = new HashSet<Cart_Item>();
        }
    
        public int order_id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total_bill { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ICollection<Cart_Item> Cart_Item { get; set; }
    }
}
