//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store2DoorDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Cart_Item = new HashSet<Cart_Item>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string description { get; set; }
        public string stock { get; set; }
        public string quantity_type { get; set; }
        public string product_type { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual ICollection<Cart_Item> Cart_Item { get; set; }
        public virtual Category Category { get; set; }
        public virtual ProductImage ProductImage { get; set; }
    }
}
